version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cubicanet_backend
    env_file:
      - .env.backend
    expose:
      - "8000" # Solo disponible dentro de la red de Docker
    restart: unless-stopped
    networks:
      - cubicanet

  frontend:
    build:
      context: ./Frontend/sistema-cubicanet
      dockerfile: Dockerfile
      args:
        # El frontend hablará con el backend vía /api (mismo origen)
        VITE_API_URL: ${VITE_API_URL:-/api}
    container_name: cubicanet_frontend
    # Publicamos el puerto 80 del contenedor SOLO en la IP de ZeroTier del Droplet.
    # IMPORTANTE: define ZT_BIND_IP en tu .env al valor de la IP de ZeroTier del Droplet, ej. 192.168.100.123
    ports:
      - "${ZT_BIND_IP}:80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cubicanet

networks:
  cubicanet: