version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cubicanet_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=192.168.100.149
      - DB_PORT=5432
      - DB_USER=benjamin
      - DB_PASSWORD=Ben1258
      - DB_NAME=cubicanet
      - FLASK_ENV=development
    networks:
      - cubicanet
  frontend:
    build:
      context: ./Frontend/sistema-cubicanet
      dockerfile: Dockerfile
    container_name: cubicanet_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend/sistema-cubicanet:/app
    depends_on:
      - backend
    networks:
      - cubicanet
networks:
  cubicanet: