version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cubicanet_backend
    env_file:
      - .env.backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Puedes dejar solo 'expose' si no quieres publicar a host:
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - cubicanet

  frontend:
    build:
      context: ./Frontend/sistema-cubicanet
      dockerfile: Dockerfile
    container_name: cubicanet_frontend
    environment:
      # Para Vue CLI, las variables deben empezar con VUE_APP_
      VUE_APP_API_URL: "http://backend:8000"
    # Publica el puerto 80 del host hacia el 8080 del contenedor (dev server)
    ports:
      - "${ZT_BIND_IP}:80:8080"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cubicanet

networks:
  cubicanet: